# Site settings
title: kylin.io
email: dev@kylin.incubator.apache.org
description: Apache Kylin Home
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kyli.io" # the base hostname & protocol for your site
twitter_username: ApacheKylin
github_username:  KylinOLAP

encoding: UTF-8

# Build settings
markdown: kramdown
# Permalinks, default is pretty
permalink: pretty

# Multiple Languages Plugin
gems:           ['jekyll-multiple-languages']
# Supported Languages
languages: ['en','cn']
language_default: 'en'

# If a post of default language not set `no_fill_default_content` to true
# Its content will use to replace if the corresponding content of other languages is not exist.
# fill_default_content: true